### ISSUE TITLE
Cannot copy tree error while installing skin

### ISSUE THREAD

**Issue by Bravo555** [kotajacob/wal_steam#60]
```
$ wal-steam -w

Wal Steam cache found
Wal Steam config found
Installing skin
Traceback (most recent call last):
  File "/home/marcel/.local/bin/wal-steam", line 11, in <module>
    sys.exit(main())
  File "/home/marcel/.local/bin/wal_steam.py", line 447, in main
    checkInstall(oSys, dpi)
  File "/home/marcel/.local/bin/wal_steam.py", line 347, in checkInstall
    checkSkin(oSys, dpi)
  File "/home/marcel/.local/bin/wal_steam.py", line 231, in checkSkin
    copy_tree(METRO_COPY, os.path.join(steam_dir, SKIN_NAME))
  File "/usr/lib/python3.6/distutils/dir_util.py", line 127, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/home/marcel/.cache/wal_steam/metroZip/Metro 4.2.4': not a directory
```

**Comment by bwollmer** [comment]
I got the same problem on arch. Somehow the downlod/extraction of the metro skin doesn't work. I've only limited python knowlege so I couldn't figure out why this is happening. But as a workaround you can simply download the Metro Skin(http://metroforsteam.com/downloads/4.2.4.zip) and extract it to  /home/marcel/.cache/wal_steam/metroZip/Metro 4.2.4
and run wal_steam again.

**Comment by kotajacob** [comment]
Can you run wal_steam -v and tell me what version you're running? I should be able to work on this tonight or tomorrow morning.

**Comment by Bravo555** [comment]
I'm using version 1.2.4

**Comment by kotajacob** [comment]
It seems like on some setups wal-steam is failing to create directories and then crashing when attempting to copy into them. I'll work on replicating this and see about making a cleaner solution for the next update.

**Comment by elock37** [comment]
I can add a little bit more information. 

I had an initial error when running wal_steam -w that said there was a connection error and that it had failed to download the Metro skin. After this, I realized Steam had not been open. I open Steam and reattempt wal_steam -w. This is when I get the identical error posted in the OP. 

To fix/workaround this, I downloaded the theme zip from the Metro UI website. I unzipped the file into the folder referenced in the error (/home/$(whoami)/.cache/wal_steam/metroZip/). Re-running wal_steam -w after having the skin in the correct location completes successfully.
 
I believe the connection error and failed download begets the copy tree error.

**Comment by elock37** [comment]
After reviewing the code and running it piecemeal, I get an HTTP 403 error when I execute "urllib.request.urlretrieve(METRO_URL, METRO_ZIP)". 

This seems to be a server side issue with MetroUI. It may be intermittent or they may be denying based on HTTP headers. In either case, this will cause the future copy_tree error. The culprit seems to be the checkInstall() function as it only verifies that the .cache and .config folders exist before attempting to invoke checkSkin() without verifying that the skin directory exists.

**Comment by kotajacob** [comment]
Okay so upon deleting ~/.cache/wal_steam and running wal-steam there seems to be errors for these reasons.

1. MetroUI was rejecting requests without a user agent. (This has been fixed in #61 although I'd like to add a user agent for the MetroUIPatch download too)

2. The new url for the metro patch file from #61 is failing on some machines
https://codeload.github.com/redsigma/UPMetroSkin/zip/196feafc14deae103355b4fee1ecc4cda9288c7f

The old one below from before #61 seems to be working for me now in all my testing so I think I will switch back to this one and add a user agent unless someone is having problems with this one and has a better solution.
https://github.com/redsigma/UPMetroSkin/archive/196feafc14deae103355b4fee1ecc4cda9288c7f.zip

3. The error message everyone was getting is because it failed to download the files (either because poor connection or lately the site rejecting connections), but then when run a second time wal-steam assumed the files were downloaded. This can easily be fixed by checking for all the files each run.

I'm gonna push the fixes for 1 and 2 out with 1.2.5 as soon as I finish up testing then work on 3 for the next version since that's a bit less urgent. 

...Sorry my responses have been soo spotty I've been extremely busy this winter :( Hopefully this should fix everything up and I can work on new features like fonts and other preferences about the skin :)

**Comment by kotajacob** [comment]
Nevermind about 2. it seems like both the url's are failing every once in a while I'll just need to verify everything before applying the colors.

**Comment by emctague** [comment]
Since the issue seems to be with the reliability and behavior or the third-party server: Perhaps you could set up a small mirror server and have it auto-update from the official server on occasion to ensure you're hosting the latest version.

**Comment by kotajacob** [comment]
@emctague I was thinking about that, but I think they're copyrighted such that redistributing the files might be bad.

**Comment by emctague** [comment]
@kotajacob Perhaps you could ask for permission from the maintainers and see how they respond?

**Comment by kotajacob** [comment]
@emctague Hmmm that's a good point. I'll send them a message, but I think I'll rewrite the checkInstall functions too because either way they're pretty sloppy and should really check an md5 of the zips or something.

**Comment by emctague** [comment]
Sounds good! Just an additional suggestion, sorry: If you *do* get permission to rehost on a separate server, and you do add md5 verification, it might be a good idea to retrieve the md5s from your server, too - so you could update the current version of the skin being used without updating wal_steam itself.

**Comment by kotajacob** [comment]
Okay as of #64 being merged this issue should be "fixed" you'll want to run `wal-steam -u` to force a cache update. If that somehow doesn't work (say something here, but also) deleting ~/.cache/wal_steam and then running wal-steam with your normal options should fix it as the program now properly checks that the patch has been downloaded and uses a firefox user-agent for the downloading.

**Comment by kotajacob** [comment]
I'm pushing out 1.2.5 with these fixes here and on pip so you should be able to update to the latest version and have everything work correctly.

**Comment by Bravo555** [comment]
Issue is fixed. Thanks very much!
